# Generated by Django 4.0.6 on 2022-07-11 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('prod_country', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('material', models.CharField(max_length=100)),
                ('inner_material', models.CharField(max_length=100)),
                ('vendor_code', models.CharField(max_length=9)),
                ('color', models.CharField(max_length=50)),
                ('sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sneakers.size')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country_founded', models.CharField(max_length=100)),
                ('year_founded', models.DateField(verbose_name='Year founded')),
                ('official_name', models.CharField(max_length=200)),
                ('official_address', models.CharField(max_length=200)),
                ('importer_name', models.CharField(max_length=200, verbose_name='Importer')),
                ('importer_address', models.CharField(max_length=200)),
                ('sneakers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sneakers.sneaker')),
            ],
        ),
    ]
