# Generated by Django 4.0.6 on 2022-07-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='image',
            field=models.ImageField(blank=True, default='sneaker/no_image.jpg', null=True, upload_to='sneaker/%Y/%m/%d/'),
        ),
    ]
