# Generated by Django 4.0.6 on 2022-07-12 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 11, 29, 0, 925005, tzinfo=utc), verbose_name='date published'),
        ),
    ]
