# Generated by Django 4.0.6 on 2022-07-12 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0003_sneaker_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
