# Generated by Django 4.0.6 on 2022-07-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0005_remove_brand_sneakers_remove_category_sneakers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sneaker/%Y/%m/%d/'),
        ),
    ]
