# Generated by Django 4.0.6 on 2022-07-24 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_history',
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AV', 'Active'), ('BO', 'Bought'), ('DE', 'Denied')], default='AV', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basket.basket'),
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
